version: 2
jobs:
  build:
    working_directory: ~/pdfreplace
    docker:
      - image:  circleci/clojure:tools-deps-buster
        auth:
          username: thork
          password: $DOCKERHUB_PASSWORD
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - pdfreplace-{{ checksum "deps.edn" }}
            - pdfreplace-
      - run: mkdir -p target
      - run: ./bin/kaocha --reporter documentation
      - save_cache:
          paths:
            - ~/.m2
          key: pdfreplace-{{ checksum "deps.edn" }}
      - run: clojure -M:uberjar
      - store_artifacts:
          path: target/pdfreplace.jar
          destination: uberjar
